### ISSUE TITLE
[Bug] Using server side library node:crypto

### ISSUE THREAD

**Issue by matthewyu-okx** [lutianzhou001/aa-sdk#10]
## Background

aa-sdk is importing `node:crypto`.

<img width="610" alt="Screenshot 2024-06-28 at 11 29 53 AM" src="https://github.com/lutianzhou001/aa-sdk/assets/144645579/f8d62b2d-a18e-4ecb-b6d8-f92780db180b">

However, frontend may need additional plugin to support this modules.

![Screenshot 2024-06-28 at 11 28 51 AM](https://github.com/lutianzhou001/aa-sdk/assets/144645579/a04b5b2a-1857-4a72-9332-98a28c4ef39d)

This may becomes a barrier for developer to use this sdk.

## Suggestion 

Use another library

**Comment by lutianzhou001** [comment]
https://github.com/lutianzhou001/aa-sdk/commit/86966a5e5012b9daded67b2b1ec014b068632ade#r143634787

**Comment by lutianzhou001** [comment]
solved

**Comment by lutianzhou001** [comment]
solved,close
