### ISSUE TITLE
[Suggestion] Expose type interfaces

### ISSUE THREAD

**Issue by matthewyu-okx** [lutianzhou001/aa-sdk#14]
## Current Behavior

There are many types and interfaces. It will be helpful to devs to export them from the sdk root instead of requiring devs to search for the interfaces and types by themselves and import he specific paths.

The current import of type interface has to be with the full path of the file:
```js
import type { ExecuteCallDataArgs } from "account-abstraction-wallet-sdk/dist/packages/okxSmartAccount/types";
```

## Suggested Behavior

Export the interfaces at the `index.ts` of the sdk so that in can have the shortest import path.
For example, 
```js
import type { ExecuteCallDataArgs } from "account-abstraction-wallet-sdk";
```

The above is just an example. The suggestion is not just limited to this type or interface

**Comment by lutianzhou001** [comment]
https://github.com/lutianzhou001/aa-sdk/pull/17

**Comment by lutianzhou001** [comment]
fixed and close.
