### ISSUE TITLE
[Suggestion] Missing getAdminValidatorAndSubject()

### ISSUE THREAD

**Issue by matthewyu-okx** [lutianzhou001/aa-sdk#9]
## Background

In the old version sdk, there is a function to get the admin validator and subject of an AA.

```js
const { adminValidator, subject } = smartAccount.accountManager.getAdminValidatorAndSubject(aa.address)
```

In the new version of sdk, this function is removed and not replaced with any function. It is important for AA Web to identify whether the current signer is the owner of the AA.

**Comment by lutianzhou001** [comment]
https://github.com/lutianzhou001/aa-sdk/pull/11

**Comment by lutianzhou001** [comment]
https://github.com/lutianzhou001/aa-sdk/pull/13

**Comment by lutianzhou001** [comment]
solved and close.
